# Generated by Django 5.2.7 on 2025-10-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='history/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
